name: Production Deploy # 本番環境へのデプロイ

# on:                     # トリガーの設定
#   release:              # リリースイベント時に実行
#     branches: [main]    # ブランチの指定
#   workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy   # ジョブの名前
    runs-on: ubuntu-latest    # ランナー環境の指定
    env:
      BASE_FOLDER: ../dist  # GitHub Actions 実行時の出力先を設定 (WPの場合のみ使用)

    steps:
        - name: Get latest codel
          uses: actions/checkout@v4   # チェックアウトアクション（https://github.com/actions/checkout）

        - name: Use Node.js 20  # Node.jsのバージョン指定(distフォルダが存在している場合は不要)
          uses: actions/setup-node@v2
          with:
            node-version: '20'
          
        - name: Install dependencies and build # コンパイルの実行 (distフォルダが存在している場合は不要)
          run: |
            npm install
            npx gulp build
          working-directory: _gulp

        - name: Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5   # FTPアップロードアクション（https://github.com/SamKirkland/FTP-Deploy-Action）
          with:
              server: ${{ secrets.PROD_SERVER }}       # FTPのサーバーアドレス
              username: ${{ secrets.PROD_USERNAME }}   # FTPのユーザー名名
              password: ${{ secrets.PROD_PASSWORD }}   # FTPのパスワード
              local-dir: ./dist/                           # アップロードしたいファイルのパス
              # server-dir: /sassy-make.com/public_html/maindelectory/wp-content/themes/frisodeups/      # アップロード先のリモートパス
